// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjhW-1js11hbdDCpXBqDov5OzD6gF6_Oo',
    appId: '1:1010810302873:web:10e6fafabc15c39b2e6308',
    messagingSenderId: '1010810302873',
    projectId: 'mechfixes-app-2026',
    authDomain: 'mechfixes-app-2026.firebaseapp.com',
    storageBucket: 'mechfixes-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDleXM64T_oDdeW83VCxYrqcj8fzzxuF-c',
    appId: '1:1010810302873:android:483d6f1c5a8b45762e6308',
    messagingSenderId: '1010810302873',
    projectId: 'mechfixes-app-2026',
    storageBucket: 'mechfixes-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-j4j5bxl3y8Cxiyl1hjcWYhauuTiEppE',
    appId: '1:1010810302873:ios:571622dfaf345bf42e6308',
    messagingSenderId: '1010810302873',
    projectId: 'mechfixes-app-2026',
    storageBucket: 'mechfixes-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.mechfixes',
  );
}
